name: Node.js CI

on:
  push:
    branches: [ avl ]
  pull_request:
    branches: [ avl ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

        uses: actions/checkout@v3
      - name: ssh and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.21
          username: avl-test
          password: Avl@test
          # key: 0550250298
          port: 22
          script: |
          cd /home/avl-test/avl-server-ramy
            git pull origin main
            git status 
            nodemon app.js











